# Generated by Django 5.2.5 on 2026-01-28 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagramLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(default='line', max_length=20)),
                ('points', models.JSONField()),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='mimic_diagram_api.diagram')),
            ],
        ),
        migrations.CreateModel(
            name='DiagramNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('area', 'Area'), ('zone', 'Zone'), ('rect', 'Rectangle'), ('tank', 'Tank'), ('water-pump', 'Water Pump'), ('pipe', 'Pipe'), ('meter', 'Meter'), ('sprinkler', 'Sprinkler'), ('isolation-valve', 'Isolation Valve'), ('control-valve', 'Control Valve'), ('motor', 'Motor'), ('circle', 'Circle'), ('ellipse', 'Ellipse'), ('capsule', 'Capsule'), ('cylinder', 'Cylinder'), ('text', 'Text'), ('custom', 'Custom'), ('tee', 'Tee'), ('cross', 'Cross'), ('level-transmitter', 'Level Transmitter'), ('soil-moisture-sensor', 'Soil Moisture Sensor')], max_length=50)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('rotation', models.FloatField(blank=True, null=True)),
                ('scale_x', models.FloatField(blank=True, null=True)),
                ('scale_y', models.FloatField(blank=True, null=True)),
                ('fill', models.CharField(blank=True, max_length=50, null=True)),
                ('stroke', models.CharField(blank=True, max_length=50, null=True)),
                ('stroke_width', models.FloatField(blank=True, null=True)),
                ('opacity', models.FloatField(blank=True, null=True)),
                ('draggable', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=False)),
                ('selectable', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('resizable', models.BooleanField(default=True)),
                ('z_index', models.IntegerField(default=0)),
                ('group_id', models.UUIDField(blank=True, null=True)),
                ('style', models.JSONField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='mimic_diagram_api.diagram')),
            ],
        ),
        migrations.CreateModel(
            name='DiagramNodePort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('type', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('both', 'Both')], default='both', max_length=10)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='mimic_diagram_api.diagramnode')),
            ],
        ),
        migrations.CreateModel(
            name='DiagramLinkEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('from', 'From'), ('to', 'To')], max_length=10)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='mimic_diagram_api.diagramlink')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimic_diagram_api.diagramnode')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mimic_diagram_api.diagramnodeport')),
            ],
        ),
    ]
