# Generated by Django 5.2.5 on 2026-01-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimic_diagram_api', '0002_diagramnode_connectable'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagramnodeport',
            name='position',
            field=models.CharField(choices=[('top', 'Top'), ('right', 'Right'), ('bottom', 'Bottom'), ('left', 'Left')], default='left', max_length=10),
        ),
    ]
